---
# tasks file for tools
- name: install common packages (git, unzip, curl, wget)
  yum: name={{ item }} update_cache=yes state=latest
  with_items:
    - curl
    - git
    - unzip
    - wget
    - python-setuptools

- name: Install pip
  easy_install: name=pip

- name: Install common Python packages (ansible-cmdb)
  pip: name={{ item }} state=latest
  with_items:
    - ansible-cmdb  

