---
galaxy_info:
  author: Bert Van Vreckem
  description: Manage MariaDB on a RedHat based Linux distribution.
  license: BSD
  min_ansible_version: 22
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 23
  galaxy_tags:
    - database
    - sql
dependencies: []
