---

- hosts: controller
  become: true
  become_method: sudo

- hosts: vagrant-vm
  become: true
  become_method: sudo
  vars_files:
    - ./environments/vagrant-vm.yml
  roles:
    - base
    - ntp
    - java
    - maven
    - ansible
    - docker
    - mmonit
    - monit

- hosts: cloud-vm
  become: true
  become_method: sudo
  vars_files:
    - ./environments/cloud-vm.yml
  roles:
    - base
    - ntp
    - java
    - maven
    - ansible
    - docker
    - mmonit
    - monit
        
- hosts: molecule-ubuntu
  become: true
  become_method: sudo
  vars_files:
    - ./environments/vagrant-vm.yml
  roles:
    - base
    - ntp
    - java
    - maven
    - ansible
    - docker
#    - mmonit
    - monit

- hosts: molecule-centos
  become: true
  become_method: sudo
  vars_files:
    - ./environments/vagrant-vm.yml
  roles:
    - base
    - ntp
    - java
    - maven
    - ansible
    - docker
#    - mmonit
    - monit
