---

- hosts: controller
  become: true
  become_method: sudo

- hosts: vagrant-vm
  become: true
  become_method: sudo
  vars_files:
    - ./environments/vagrant-vm.yml
  vars:
    - docker_group_members: [vagrant]
  roles:
    - base
    - ntp
    - java
    - maven
    - ansible
    - docker
    - mmonit
    - monit
