# Multi-Machine Vagrant Configurations

playbook: "playbook.yml"

env : ["vagrant-vm", "controller" ]
#env : ["web", "testdrive", "controller" ]

ck_workspace: "~/Workspace/ck1234"

os : "minimal/trusty64"
#os : "minimal/centos6"
auto_update : false


controller:
  name : controller
  network:
    ip: 192.168.24.100
    host: controller.dev

vagrant-vm:
  name : vagrant-vm
  network:
    ip: 192.168.24.101
    host: vagrant-vm.dev


