# Multi-Machine Vagrant Configurations

playbook: "playbook.yml"

env : ["ignitor", "controller" ]
#env : ["web","ignitor", "controller" ]

#ck_workspace: "~/Workspace/ck"

os : "minimal/trusty64"
#os : "minimal/centos6"
auto_update : true

syncFolders :
  - host: vagrant/scripts
    guest: /scripts
  - host: ~/Workspace/ck
    guest: /ck
  - host: ~/Workspace/ck/jumpstart
    guest: /jumpstart
  - host: ~/Workspace/ck/ignitor
    guest: /ignitor
    
controller:
  name : controller
  network:
    ip: 192.168.24.100
    host: controller.dev

ignitor:
  name : ignitor
  network:
    ip: 192.168.24.101
    host: ignitor.dev

        
