# -*- mode: ruby -*-
# vi: set ft=ruby :
# https://www.vagrantup.com/docs/vagrantfile/tips.html

# Load in custom vagrant settings
require "yaml"
require File.join(File.dirname(__FILE__), "vagrant/lib/Orchestrator")

settings = File.file?("vagrant/config.yml") ? YAML.load_file("vagrant/config.yml") : {}


VAGRANTFILE_API_VERSION ||= "2".freeze

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	ck_workspace = settings["ck_workspace"]
	playbook = settings["playbook"]
	env = settings["env"]
	os = settings["os"]
  auto_update =  settings["auto_update"]

	Orchestrator.installPlugins
  
	(0..env.length-1).each do |node|
			name = settings[env[node]]["name"]
			ip = settings[env[node]]["network"]["ip"]
			hostname = settings[env[node]]["network"]["host"]
			syncFolders = settings[env[node]]["syncFolders"]
      
			Orchestrator.createVM os, auto_update, config
			Orchestrator.configureVM name,ip,hostname, playbook, config
      Orchestrator.syncFolders syncFolders, config
  end
end
