---
dependencies: []

galaxy_info:
  author: Tobias Schifftner
  description: Installs M/Monit on Debian/Ubuntu linux servers.
  company: ambimax® GmbH
  license: MIT
  min_ansible_version: 2.1
  platforms:
  - name: Debian
    versions:
    - jessie
  - name: Ubuntu
    versions:
    - precise
    - trusty
  galaxy_tags:
    - ubuntu
    - debian
    - mmonit
    - m/monit
