---

- name: Install EPEL repo.
  yum:
    name: "http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm"
    state: present
  register: result

- name: pkg - Install package
  yum:
    name: monit
    state: present
