---


- name: Ensure the Nginx conf.d Directory exists.
  file:
    dest: "/etc/nginx/conf.d"
    mode: 0755
    owner: root
    state: directory

- name: Deploy Application Nginx Configuration
  template:
    src: "b2b.conf.j2"
    dest: "/etc/nginx/conf.d/b2b.conf"
    mode: 0755
    owner: root
  tags:
    - configure

- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Restart nginx
  service: name=nginx state=restarted
  become: true
  tags:
    - configure
